apiVersion: v1
data:
  logstash.conf: |
      input {
          kafka {
              bootstrap_servers => "10.1.0.15:9092"
              group_id => "logstash-test"
              topics => ["log-test"]
              codec => json
          }
      }

      output {
          elasticsearch {
              hosts => "http://172.28.255.219:9200"
              index => "ccs-log"
          }
      }
kind: ConfigMap
metadata:
  name: logstash-consumer-config